export const listOfBooks = [
    {
      author: "Chinua Achebe",
      country: "Nigeria",
      imageLink: "https://i.ibb.co/nL830Gc/things-fall-apart.jpg",
      is_liked: true,
      language: "English",
      link: "https://en.wikipedia.org/wiki/Things_Fall_Apart ",
      pages: 209,
      price: 22,
      rating: 1,
      reviews: 126,
      title: "Things Fall Apart",
      year: 1958
    },
    {
      author: "Hans Christian Andersen",
      country: "Denmark",
      imageLink: "https://i.ibb.co/b68nnm3/fairy-tales.jpg",
      is_liked: false,
      language: "Danish",
      link: "https://en.wikipedia.org/wiki/Fairy_Tales_Told_for_Children._First_Collection. ",
      pages: 784,
      price: 73,
      rating: 4,
      reviews: 440,
      title: "Fairy tales",
      year: 1836
    },
    {
      author: "Dante Alighieri",
      country: "Italy",
      imageLink: "https://i.ibb.co/2WKMPcY/the-divine-comedy.jpg",
      is_liked: true,
      language: "Italian",
      link: "https://en.wikipedia.org/wiki/Divine_Comedy ",
      pages: 928,
      price: 64,
      rating: 1,
      reviews: 364,
      title: "The Divine Comedy",
      year: 1315
    },
    {
      author: "Unknown",
      country: "Sumer and Akkadian Empire",
      imageLink: "https://i.ibb.co/3yJzJV7/the-epic-of-gilgamesh.jpg",
      is_liked: false,
      language: "Akkadian",
      link: "https://en.wikipedia.org/wiki/Epic_of_Gilgamesh ",
      pages: 160,
      price: 39,
      rating: 1,
      reviews: 334,
      title: "The Epic Of Gilgamesh",
      year: 1700
    },
    {
      author: "Unknown",
      country: "Achaemenid Empire",
      imageLink: "https://i.ibb.co/gD4R8JZ/the-book-of-job.jpg",
      is_liked: true,
      language: "Hebrew",
      link: "https://en.wikipedia.org/wiki/Book_of_Job ",
      pages: 176,
      price: 94,
      rating: 1,
      reviews: 189,
      title: "The Book Of Job",
      year: 600
    },
    {
      author: "Unknown",
      country: "India/Iran/Iraq/Egypt/Tajikistan",
      imageLink: "https://i.ibb.co/BZ4gzdP/one-thousand-and-one-nights.jpg",
      is_liked: false,
      language: "Arabic",
      link: "https://en.wikipedia.org/wiki/One_Thousand_and_One_Nights ",
      pages: 288,
      price: 99,
      rating: 2,
      reviews: 18,
      title: "One Thousand and One Nights",
      year: 1200
    },
    {
      author: "Unknown",
      country: "Iceland",
      imageLink: "https://i.ibb.co/Qjzw0Ck/njals-saga.jpg",
      is_liked: true,
      language: "Old Norse",
      link: "https://en.wikipedia.org/wiki/Nj%C3%A1ls_saga ",
      pages: 384,
      price: 67,
      rating: 2,
      reviews: 480,
      title: "Njál's Saga",
      year: 1350
    },
    {
      author: "Jane Austen",
      country: "United Kingdom",
      imageLink: "https://i.ibb.co/FzdWhx0/pride-and-prejudice.jpg",
      is_liked: false,
      language: "English",
      link: "https://en.wikipedia.org/wiki/Pride_and_Prejudice ",
      pages: 226,
      price: 77,
      rating: 3,
      reviews: 158,
      title: "Pride and Prejudice",
      year: 1813
    },
    {
      author: "Honoré de Balzac",
      country: "France",
      imageLink: "https://i.ibb.co/NyF3p1b/le-pere-goriot.jpg",
      is_liked: true,
      language: "French",
      link: "https://en.wikipedia.org/wiki/Le_P%C3%A8re_Goriot ",
      pages: 443,
      price: 12,
      rating: 5,
      reviews: 346,
      title: "Le Père Goriot",
      year: 1835
    },
    {
      author: "Samuel Beckett",
      country: "Republic of Ireland",
      imageLink: "https://i.ibb.co/VVjvbG4/molloy-malone-dies-the-unnamable.jpg",
      is_liked: false,
      language: "French, English",
      link: "https://en.wikipedia.org/wiki/Molloy_(novel) ",
      pages: 256,
      price: 11,
      rating: 4,
      reviews: 160,
      title: "Molloy, Malone Dies, The Unnamable, the trilogy",
      year: 1952
    },
    {
      author: "Jorge Luis Borges",
      country: "Argentina",
      imageLink: "https://i.ibb.co/b34Nyk5/ficciones.jpg",
      is_liked: false,
      language: "Spanish",
      link: "https://en.wikipedia.org/wiki/Ficciones ",
      pages: 224,
      price: 28,
      rating: 4,
      reviews: 385,
      title: "Ficciones",
      year: 1965
    },
    {
      author: "Emily Brontë",
      country: "United Kingdom",
      imageLink: "https://i.ibb.co/1nmMz57/wuthering-heights.jpg",
      is_liked: true,
      language: "English",
      link: "https://en.wikipedia.org/wiki/Wuthering_Heights ",
      pages: 342,
      price: 22,
      rating: 2,
      reviews: 191,
      title: "Wuthering Heights",
      year: 1847
    },
    {
      author: "Albert Camus",
      country: "Algeria, French Empire",
      imageLink: "https://i.ibb.co/y6TWnbN/l-etranger.jpg",
      is_liked: false,
      language: "French",
      link: "https://en.wikipedia.org/wiki/The_Stranger_(novel) ",
      pages: 185,
      price: 6,
      rating: 1,
      reviews: 339,
      title: "The Stranger",
      year: 1942
    },
    {
      author: "Paul Celan",
      country: "Romania, France",
      imageLink: "https://i.ibb.co/1QPKkXG/poems-paul-celan.jpg",
      is_liked: true,
      language: "German",
      link: " ",
      pages: 320,
      price: 78,
      rating: 2,
      reviews: 466,
      title: "Poems",
      year: 1952
    },
    {
      author: "Louis-Ferdinand Céline",
      country: "France",
      imageLink: "https://i.ibb.co/k4p7TXK/voyage-au-bout-de-la-nuit.jpg",
      is_liked: false,
      language: "French",
      link: "https://en.wikipedia.org/wiki/Journey_to_the_End_of_the_Night ",
      pages: 505,
      price: 8,
      rating: 2,
      reviews: 367,
      title: "Journey to the End of the Night",
      year: 1932
    },
    {
      author: "Miguel de Cervantes",
      country: "Spain",
      imageLink: "https://i.ibb.co/tKJn4Hf/don-quijote-de-la-mancha.jpg",
      is_liked: true,
      language: "Spanish",
      link: "https://en.wikipedia.org/wiki/Don_Quixote ",
      pages: 1056,
      price: 92,
      rating: 2,
      reviews: 335,
      title: "Don Quijote De La Mancha",
      year: 1610
    },
    {
      author: "Geoffrey Chaucer",
      country: "England",
      imageLink: "https://i.ibb.co/bWxbMQk/the-canterbury-tales.jpg",
      is_liked: false,
      language: "English",
      link: "https://en.wikipedia.org/wiki/The_Canterbury_Tales ",
      pages: 544,
      price: 8,
      rating: 4,
      reviews: 205,
      title: "The Canterbury Tales",
      year: 1450
    },
    {
      author: "Anton Chekhov",
      country: "Russia",
      imageLink: "https://i.ibb.co/26mXFyL/stories-of-anton-chekhov.jpg",
      is_liked: true,
      language: "Russian",
      link: "https://en.wikipedia.org/wiki/List_of_short_stories_by_Anton_Chekhov ",
      pages: 194,
      price: 69,
      rating: 0,
      reviews: 382,
      title: "Stories",
      year: 1886
    },
    {
      author: "Joseph Conrad",
      country: "United Kingdom",
      imageLink: "https://i.ibb.co/2tcnYtV/nostromo.jpg",
      is_liked: false,
      language: "English",
      link: "https://en.wikipedia.org/wiki/Nostromo ",
      pages: 320,
      price: 5,
      rating: 1,
      reviews: 330,
      title: "Nostromo",
      year: 1904
    },
    {
      author: "Charles Dickens",
      country: "United Kingdom",
      imageLink: "https://i.ibb.co/3y0MYPP/great-expectations.jpg",
      is_liked: true,
      language: "English",
      link: "https://en.wikipedia.org/wiki/Great_Expectations ",
      pages: 194,
      price: 56,
      rating: 3,
      reviews: 327,
      title: "Great Expectations",
      year: 1861
    },
    {
      author: "Denis Diderot",
      country: "France",
      imageLink: "https://i.ibb.co/5YHmGDM/jacques-the-fatalist.jpg",
      is_liked: false,
      language: "French",
      link: "https://en.wikipedia.org/wiki/Jacques_the_Fatalist ",
      pages: 596,
      price: 93,
      rating: 4,
      reviews: 370,
      title: "Jacques the Fatalist",
      year: 1796
    },
    {
      author: "Alfred Döblin",
      country: "Germany",
      imageLink: "https://i.ibb.co/82f5pPf/berlin-alexanderplatz.jpg",
      is_liked: true,
      language: "German",
      link: "https://en.wikipedia.org/wiki/Berlin_Alexanderplatz ",
      pages: 600,
      price: 10,
      rating: 5,
      reviews: 376,
      title: "Berlin Alexanderplatz",
      year: 1929
    },
    {
      author: "Fyodor Dostoevsky",
      country: "Russia",
      imageLink: "https://i.ibb.co/41S1qVF/crime-and-punishment.jpg",
      is_liked: false,
      language: "Russian",
      link: "https://en.wikipedia.org/wiki/Crime_and_Punishment ",
      pages: 551,
      price: 22,
      rating: 2,
      reviews: 116,
      title: "Crime and Punishment",
      year: 1866
    },
    {
      author: "Fyodor Dostoevsky",
      country: "Russia",
      imageLink: "https://i.ibb.co/7yLybjn/the-idiot.jpg",
      is_liked: true,
      language: "Russian",
      link: "https://en.wikipedia.org/wiki/The_Idiot ",
      pages: 656,
      price: 12,
      rating: 2,
      reviews: 387,
      title: "The Idiot",
      year: 1869
    },
    {
      author: "Fyodor Dostoevsky",
      country: "Russia",
      imageLink: "https://i.ibb.co/wBP1bz4/the-possessed.jpg",
      is_liked: false,
      language: "Russian",
      link: "https://en.wikipedia.org/wiki/Demons_(Dostoyevsky_novel) ",
      pages: 768,
      price: 19,
      rating: 1,
      reviews: 125,
      title: "The Possessed",
      year: 1872
    },
    {
      author: "Fyodor Dostoevsky",
      country: "Russia",
      imageLink: "https://i.ibb.co/PhHGs60/the-brothers-karamazov.jpg",
      is_liked: true,
      language: "Russian",
      link: "https://en.wikipedia.org/wiki/The_Brothers_Karamazov ",
      pages: 824,
      price: 67,
      rating: 2,
      reviews: 357,
      title: "The Brothers Karamazov",
      year: 1880
    },
    {
      author: "George Eliot",
      country: "United Kingdom",
      imageLink: "https://i.ibb.co/8c6kP2q/middlemarch.jpg",
      is_liked: false,
      language: "English",
      link: "https://en.wikipedia.org/wiki/Middlemarch ",
      pages: 800,
      price: 98,
      rating: 4,
      reviews: 119,
      title: "Middlemarch",
      year: 1871
    },
    {
      author: "Ralph Ellison",
      country: "United States",
      imageLink: "https://i.ibb.co/w7kYq5c/invisible-man.jpg",
      is_liked: true,
      language: "English",
      link: "https://en.wikipedia.org/wiki/Invisible_Man ",
      pages: 581,
      price: 95,
      rating: 4,
      reviews: 498,
      title: "Invisible Man",
      year: 1952
    },
    {
      author: "Euripides",
      country: "Greece",
      imageLink: "https://i.ibb.co/jMK79GL/medea.jpg",
      is_liked: false,
      language: "Greek",
      link: "https://en.wikipedia.org/wiki/Medea_(play) ",
      pages: 104,
      price: 1,
      rating: 1,
      reviews: 269,
      title: "Medea",
      year: 431
    },
    {
      author: "William Faulkner",
      country: "United States",
      imageLink: "https://i.ibb.co/8czm7Jm/absalom-absalom.jpg",
      is_liked: true,
      language: "English",
      link: "https://en.wikipedia.org/wiki/Absalom,_Absalom! ",
      pages: 313,
      price: 73,
      rating: 2,
      reviews: 80,
      title: "Absalom, Absalom!",
      year: 1936
    },
    {
      author: "William Faulkner",
      country: "United States",
      imageLink: "https://i.ibb.co/wwBTsTb/the-sound-and-the-fury.jpg",
      is_liked: false,
      language: "English",
      link: "https://en.wikipedia.org/wiki/The_Sound_and_the_Fury ",
      pages: 326,
      price: 92,
      rating: 3,
      reviews: 461,
      title: "The Sound and the Fury",
      year: 1929
    },
    {
      author: "Gustave Flaubert",
      country: "France",
      imageLink: "https://i.ibb.co/jrxjSxr/madame-bovary.jpg",
      is_liked: true,
      language: "French",
      link: "https://en.wikipedia.org/wiki/Madame_Bovary ",
      pages: 528,
      price: 63,
      rating: 3,
      reviews: 2,
      title: "Madame Bovary",
      year: 1857
    },
    {
      author: "Gustave Flaubert",
      country: "France",
      imageLink: "https://i.ibb.co/cgT6FC1/l-education-sentimentale.jpg",
      is_liked: false,
      language: "French",
      link: "https://en.wikipedia.org/wiki/Sentimental_Education ",
      pages: 606,
      price: 28,
      rating: 4,
      reviews: 266,
      title: "Sentimental Education",
      year: 1869
    },
    {
      author: "Federico García Lorca",
      country: "Spain",
      imageLink: "https://i.ibb.co/VBKW37y/gypsy-ballads.jpg",
      is_liked: true,
      language: "Spanish",
      link: "https://en.wikipedia.org/wiki/Gypsy_Ballads ",
      pages: 218,
      price: 54,
      rating: 0,
      reviews: 430,
      title: "Gypsy Ballads",
      year: 1928
    },
    {
      author: "Gabriel García Márquez",
      country: "Colombia",
      imageLink: "https://i.ibb.co/p4XWr7j/one-hundred-years-of-solitude.jpg",
      is_liked: false,
      language: "Spanish",
      link: "https://en.wikipedia.org/wiki/One_Hundred_Years_of_Solitude ",
      pages: 417,
      price: 69,
      rating: 0,
      reviews: 405,
      title: "One Hundred Years of Solitude",
      year: 1967
    },
    {
      author: "Gabriel García Márquez",
      country: "Colombia",
      imageLink: "https://i.ibb.co/mhLTx1F/love-in-the-time-of-cholera.jpg",
      is_liked: true,
      language: "Spanish",
      link: "https://en.wikipedia.org/wiki/Love_in_the_Time_of_Cholera ",
      pages: 368,
      price: 73,
      rating: 3,
      reviews: 402,
      title: "Love in the Time of Cholera",
      year: 1985
    },
    {
      author: "Johann Wolfgang von Goethe",
      country: "Saxe-Weimar",
      imageLink: "https://i.ibb.co/zGPYyP0/faust.jpg",
      is_liked: false,
      language: "German",
      link: "https://en.wikipedia.org/wiki/Goethe%27s_Faust ",
      pages: 158,
      price: 28,
      rating: 1,
      reviews: 169,
      title: "Faust",
      year: 1832
    },
    {
      author: "Nikolai Gogol",
      country: "Russia",
      imageLink: "https://i.ibb.co/fkkt2L1/dead-souls.jpg",
      is_liked: true,
      language: "Russian",
      link: "https://en.wikipedia.org/wiki/Dead_Souls ",
      pages: 432,
      price: 86,
      rating: 1,
      reviews: 144,
      title: "Dead Souls",
      year: 1842
    },
    {
      author: "Günter Grass",
      country: "Germany",
      imageLink: "https://i.ibb.co/pJHmDfW/the-tin-drum.jpg",
      is_liked: false,
      language: "German",
      link: "https://en.wikipedia.org/wiki/The_Tin_Drum ",
      pages: 600,
      price: 52,
      rating: 1,
      reviews: 199,
      title: "The Tin Drum",
      year: 1959
    },
    {
      author: "João Guimarães Rosa",
      country: "Brazil",
      imageLink: "https://i.ibb.co/bHMmFbz/the-devil-to-pay-in-the-backlands.jpg",
      is_liked: true,
      language: "Portuguese",
      link: "https://en.wikipedia.org/wiki/The_Devil_to_Pay_in_the_Backlands ",
      pages: 494,
      price: 53,
      rating: 4,
      reviews: 326,
      title: "The Devil to Pay in the Backlands",
      year: 1956
    },
    {
      author: "Knut Hamsun",
      country: "Norway",
      imageLink: "https://i.ibb.co/x6v8k6R/hunger.jpg",
      is_liked: false,
      language: "Norwegian",
      link: "https://en.wikipedia.org/wiki/Hunger_(Hamsun_novel) ",
      pages: 176,
      price: 48,
      rating: 5,
      reviews: 425,
      title: "Hunger",
      year: 1890
    },
    {
      author: "Ernest Hemingway",
      country: "United States",
      imageLink: "https://i.ibb.co/5cLmWyd/the-old-man-and-the-sea.jpg",
      is_liked: true,
      language: "English",
      link: "https://en.wikipedia.org/wiki/The_Old_Man_and_the_Sea ",
      pages: 128,
      price: 95,
      rating: 1,
      reviews: 475,
      title: "The Old Man and the Sea",
      year: 1952
    },
    {
      author: "Homer",
      country: "Greece",
      imageLink: "https://i.ibb.co/fDbDpfz/the-iliad-of-homer.jpg",
      is_liked: false,
      language: "Greek",
      link: "https://en.wikipedia.org/wiki/Iliad ",
      pages: 608,
      price: 28,
      rating: 3,
      reviews: 141,
      title: "Iliad",
      year: 735
    },
    {
      author: "Homer",
      country: "Greece",
      imageLink: "https://i.ibb.co/wpYr2bz/the-odyssey-of-homer.jpg",
      is_liked: true,
      language: "Greek",
      link: "https://en.wikipedia.org/wiki/Odyssey ",
      pages: 374,
      price: 6,
      rating: 1,
      reviews: 439,
      title: "Odyssey",
      year: 800
    },
    {
      author: "Henrik Ibsen",
      country: "Norway",
      imageLink: "https://i.ibb.co/QfHwZ3G/a-Dolls-house.jpg",
      is_liked: false,
      language: "Norwegian",
      link: "https://en.wikipedia.org/wiki/A_Doll%27s_House ",
      pages: 68,
      price: 98,
      rating: 1,
      reviews: 282,
      title: "A Doll's House",
      year: 1879
    },
    {
      author: "James Joyce",
      country: "Irish Free State",
      imageLink: "https://i.ibb.co/3YV57ZY/ulysses.jpg",
      is_liked: true,
      language: "English",
      link: "https://en.wikipedia.org/wiki/Ulysses_(novel) ",
      pages: 228,
      price: 73,
      rating: 2,
      reviews: 302,
      title: "Ulysses",
      year: 1922
    },
    {
      author: "Franz Kafka",
      country: "Czechoslovakia",
      imageLink: "https://i.ibb.co/84V9Mc2/stories-of-franz-kafka.jpg",
      is_liked: false,
      language: "German",
      link: "https://en.wikipedia.org/wiki/Franz_Kafka_bibliography#Short_stories ",
      pages: 488,
      price: 6,
      rating: 4,
      reviews: 301,
      title: "Stories",
      year: 1924
    },
    {
      author: "Franz Kafka",
      country: "Czechoslovakia",
      imageLink: "https://i.ibb.co/LzFggPx/the-trial.jpg",
      is_liked: true,
      language: "German",
      link: "https://en.wikipedia.org/wiki/The_Trial ",
      pages: 160,
      price: 48,
      rating: 2,
      reviews: 390,
      title: "The Trial",
      year: 1925
    },
    {
      author: "Franz Kafka",
      country: "Czechoslovakia",
      imageLink: "https://i.ibb.co/DfMK5tc/the-castle.jpg",
      is_liked: false,
      language: "German",
      link: "https://en.wikipedia.org/wiki/The_Castle_(novel) ",
      pages: 352,
      price: 25,
      rating: 4,
      reviews: 195,
      title: "The Castle",
      year: 1926
    },
    {
      author: "Kālidāsa",
      country: "India",
      imageLink: "https://i.ibb.co/fHDNVLs/the-recognition-of-shakuntala.jpg",
      is_liked: true,
      language: "Sanskrit",
      link: "https://en.wikipedia.org/wiki/Abhij%C3%B1%C4%81na%C5%9B%C4%81kuntalam ",
      pages: 147,
      price: 100,
      rating: 3,
      reviews: 459,
      title: "The recognition of Shakuntala",
      year: 150
    },
    {
      author: "Yasunari Kawabata",
      country: "Japan",
      imageLink: "https://i.ibb.co/QCtnJQg/the-sound-of-the-mountain.jpg",
      is_liked: false,
      language: "Japanese",
      link: "https://en.wikipedia.org/wiki/The_Sound_of_the_Mountain ",
      pages: 288,
      price: 29,
      rating: 2,
      reviews: 338,
      title: "The Sound of the Mountain",
      year: 1954
    },
    {
      author: "Nikos Kazantzakis",
      country: "Greece",
      imageLink: "https://i.ibb.co/qxczwVL/zorba-the-greek.jpg",
      is_liked: true,
      language: "Greek",
      link: "https://en.wikipedia.org/wiki/Zorba_the_Greek ",
      pages: 368,
      price: 1,
      rating: 2,
      reviews: 256,
      title: "Zorba the Greek",
      year: 1946
    },
    {
      author: "D. H. Lawrence",
      country: "United Kingdom",
      imageLink: "https://i.ibb.co/ZJzG7ss/sons-and-lovers.jpg",
      is_liked: false,
      language: "English",
      link: "https://en.wikipedia.org/wiki/Sons_and_Lovers ",
      pages: 432,
      price: 24,
      rating: 4,
      reviews: 201,
      title: "Sons and Lovers",
      year: 1913
    },
    {
      author: "Halldór Laxness",
      country: "Iceland",
      imageLink: "https://i.ibb.co/3ChRPL9/independent-people.jpg",
      is_liked: true,
      language: "Icelandic",
      link: "https://en.wikipedia.org/wiki/Independent_People ",
      pages: 470,
      price: 82,
      rating: 3,
      reviews: 174,
      title: "Independent People",
      year: 1934
    },
    {
      author: "Giacomo Leopardi",
      country: "Italy",
      imageLink: "https://i.ibb.co/fQxwCF3/poems-giacomo-leopardi.jpg",
      is_liked: false,
      language: "Italian",
      link: " ",
      pages: 184,
      price: 52,
      rating: 5,
      reviews: 203,
      title: "Poems",
      year: 1818
    },
    {
      author: "Doris Lessing",
      country: "United Kingdom",
      imageLink: "https://i.ibb.co/1RngDP3/the-golden-notebook.jpg",
      is_liked: true,
      language: "English",
      link: "https://en.wikipedia.org/wiki/The_Golden_Notebook ",
      pages: 688,
      price: 81,
      rating: 1,
      reviews: 428,
      title: "The Golden Notebook",
      year: 1962
    },
    {
      author: "Astrid Lindgren",
      country: "Sweden",
      imageLink: "https://i.ibb.co/RPGkqMY/pippi-longstocking.jpg",
      is_liked: false,
      language: "Swedish",
      link: "https://en.wikipedia.org/wiki/Pippi_Longstocking ",
      pages: 160,
      price: 20,
      rating: 4,
      reviews: 330,
      title: "Pippi Longstocking",
      year: 1945
    },
    {
      author: "Lu Xun",
      country: "China",
      imageLink: "https://i.ibb.co/kXGZBXN/diary-of-a-madman.jpg",
      is_liked: true,
      language: "Chinese",
      link: "https://en.wikipedia.org/wiki/A_Madman%27s_Diary ",
      pages: 389,
      price: 78,
      rating: 3,
      reviews: 227,
      title: "Diary of a Madman",
      year: 1918
    },
    {
      author: "Naguib Mahfouz",
      country: "Egypt",
      imageLink: "https://i.ibb.co/Y79F4xk/children-of-gebelawi.jpg",
      is_liked: false,
      language: "Arabic",
      link: "https://en.wikipedia.org/wiki/Children_of_Gebelawi ",
      pages: 355,
      price: 54,
      rating: 5,
      reviews: 434,
      title: "Children of Gebelawi",
      year: 1959
    },
    {
      author: "Thomas Mann",
      country: "Germany",
      imageLink: "https://i.ibb.co/w0L8kjR/buddenbrooks.jpg",
      is_liked: true,
      language: "German",
      link: "https://en.wikipedia.org/wiki/Buddenbrooks ",
      pages: 736,
      price: 58,
      rating: 5,
      reviews: 13,
      title: "Buddenbrooks",
      year: 1901
    },
    {
      author: "Thomas Mann",
      country: "Germany",
      imageLink: "https://i.ibb.co/r6T7Bjk/the-magic-mountain.jpg",
      is_liked: false,
      language: "German",
      link: "https://en.wikipedia.org/wiki/The_Magic_Mountain ",
      pages: 720,
      price: 71,
      rating: 1,
      reviews: 442,
      title: "The Magic Mountain",
      year: 1924
    },
    {
      author: "Herman Melville",
      country: "United States",
      imageLink: "https://i.ibb.co/HpcR5X3/moby-dick.jpg",
      is_liked: true,
      language: "English",
      link: "https://en.wikipedia.org/wiki/Moby-Dick ",
      pages: 378,
      price: 31,
      rating: 0,
      reviews: 309,
      title: "Moby Dick",
      year: 1851
    },
    {
      author: "Michel de Montaigne",
      country: "France",
      imageLink: "https://i.ibb.co/5Y4LNNP/essais.jpg",
      is_liked: false,
      language: "French",
      link: "https://en.wikipedia.org/wiki/Essays_(Montaigne) ",
      pages: 404,
      price: 41,
      rating: 2,
      reviews: 172,
      title: "Essays",
      year: 1595
    },
    {
      author: "Elsa Morante",
      country: "Italy",
      imageLink: "https://i.ibb.co/PjYRSxX/history.jpg",
      is_liked: true,
      language: "Italian",
      link: "https://en.wikipedia.org/wiki/History_(novel) ",
      pages: 600,
      price: 17,
      rating: 3,
      reviews: 149,
      title: "History",
      year: 1974
    },
    {
      author: "Toni Morrison",
      country: "United States",
      imageLink: "https://i.ibb.co/0FLNP4F/beloved.jpg",
      is_liked: false,
      language: "English",
      link: "https://en.wikipedia.org/wiki/Beloved_(novel) ",
      pages: 321,
      price: 97,
      rating: 3,
      reviews: 385,
      title: "Beloved",
      year: 1987
    },
    {
      author: "Murasaki Shikibu",
      country: "Japan",
      imageLink: "https://i.ibb.co/80Q07n7/the-tale-of-genji.jpg",
      is_liked: true,
      language: "Japanese",
      link: "https://en.wikipedia.org/wiki/The_Tale_of_Genji ",
      pages: 1360,
      price: 96,
      rating: 1,
      reviews: 430,
      title: "The Tale of Genji",
      year: 1006
    },
    {
      author: "Robert Musil",
      country: "Austria",
      imageLink: "https://i.ibb.co/Th3s8jy/the-man-without-qualities.jpg",
      is_liked: false,
      language: "German",
      link: "https://en.wikipedia.org/wiki/The_Man_Without_Qualities ",
      pages: 365,
      price: 77,
      rating: 4,
      reviews: 270,
      title: "The Man Without Qualities",
      year: 1931
    },
    {
      author: "Vladimir Nabokov",
      country: "Russia/United States",
      imageLink: "https://i.ibb.co/MnbDJDW/lolita.jpg",
      is_liked: true,
      language: "English",
      link: "https://en.wikipedia.org/wiki/Lolita ",
      pages: 317,
      price: 22,
      rating: 1,
      reviews: 253,
      title: "Lolita",
      year: 1955
    },
    {
      author: "George Orwell",
      country: "United Kingdom",
      imageLink: "https://i.ibb.co/RjVhPhV/nineteen-eighty-four.jpg",
      is_liked: false,
      language: "English",
      link: "https://en.wikipedia.org/wiki/Nineteen_Eighty-Four ",
      pages: 272,
      price: 74,
      rating: 2,
      reviews: 304,
      title: "Nineteen Eighty-Four",
      year: 1949
    },
    {
      author: "Ovid",
      country: "Roman Empire",
      imageLink: "https://i.ibb.co/V9MCthf/the-metamorphoses-of-ovid.jpg",
      is_liked: true,
      language: "Classical Latin",
      link: "https://en.wikipedia.org/wiki/Metamorphoses ",
      pages: 576,
      price: 74,
      rating: 1,
      reviews: 418,
      title: "Metamorphoses",
      year: 100
    },
    {
      author: "Fernando Pessoa",
      country: "Portugal",
      imageLink: "https://i.ibb.co/rH2F9cx/the-book-of-disquiet.jpg",
      is_liked: false,
      language: "Portuguese",
      link: "https://en.wikipedia.org/wiki/The_Book_of_Disquiet ",
      pages: 272,
      price: 10,
      rating: 1,
      reviews: 143,
      title: "The Book of Disquiet",
      year: 1928
    },
    {
      author: "Edgar Allan Poe",
      country: "United States",
      imageLink: "https://i.ibb.co/FxnyWdT/tales-and-poems-of-edgar-allan-poe.jpg",
      is_liked: true,
      language: "English",
      link: "https://en.wikipedia.org/wiki/Edgar_Allan_Poe_bibliography#Tales ",
      pages: 842,
      price: 37,
      rating: 1,
      reviews: 444,
      title: "Tales",
      year: 1950
    },
    {
      author: "Marcel Proust",
      country: "France",
      imageLink: "https://i.ibb.co/dQpvGg9/a-la-recherche-du-temps-perdu.jpg",
      is_liked: false,
      language: "French",
      link: "https://en.wikipedia.org/wiki/In_Search_of_Lost_Time ",
      pages: 2408,
      price: 83,
      rating: 2,
      reviews: 449,
      title: "In Search of Lost Time",
      year: 1920
    },
    {
      author: "François Rabelais",
      country: "France",
      imageLink: "https://i.ibb.co/4Tm24NT/gargantua-and-pantagruel.jpg",
      is_liked: true,
      language: "French",
      link: "https://en.wikipedia.org/wiki/Gargantua_and_Pantagruel ",
      pages: 623,
      price: 23,
      rating: 3,
      reviews: 233,
      title: "Gargantua and Pantagruel",
      year: 1533
    },
    {
      author: "Juan Rulfo",
      country: "Mexico",
      imageLink: "https://i.ibb.co/P143Nfj/pedro-paramo.jpg",
      is_liked: false,
      language: "Spanish",
      link: "https://en.wikipedia.org/wiki/Pedro_P%C3%A1ramo ",
      pages: 124,
      price: 30,
      rating: 5,
      reviews: 203,
      title: "Pedro Páramo",
      year: 1955
    },
    {
      author: "Rumi",
      country: "Sultanate of Rum",
      imageLink: "https://i.ibb.co/VDMCVwP/the-masnavi.jpg",
      is_liked: true,
      language: "Persian",
      link: "https://en.wikipedia.org/wiki/Masnavi ",
      pages: 438,
      price: 67,
      rating: 1,
      reviews: 432,
      title: "The Masnavi",
      year: 1236
    },
    {
      author: "Salman Rushdie",
      country: "United Kingdom, India",
      imageLink: "https://i.ibb.co/gwj73Jr/midnights-children.jpg",
      is_liked: false,
      language: "English",
      link: "https://en.wikipedia.org/wiki/Midnight%27s_Children ",
      pages: 536,
      price: 64,
      rating: 1,
      reviews: 369,
      title: "Midnight's Children",
      year: 1981
    },
    {
      author: "Saadi",
      country: "Persia, Persian Empire",
      imageLink: "https://i.ibb.co/MRw9h4Y/bostan.jpg",
      is_liked: true,
      language: "Persian",
      link: "https://en.wikipedia.org/wiki/Bustan_(book) ",
      pages: 298,
      price: 57,
      rating: 4,
      reviews: 141,
      title: "Bostan",
      year: 1257
    },
    {
      author: "Tayeb Salih",
      country: "Sudan",
      imageLink: "https://i.ibb.co/WPyKcM6/season-of-migration-to-the-north.jpg",
      is_liked: false,
      language: "Arabic",
      link: "https://en.wikipedia.org/wiki/Season_of_Migration_to_the_North ",
      pages: 139,
      price: 21,
      rating: 1,
      reviews: 288,
      title: "Season of Migration to the North",
      year: 1966
    },
    {
      author: "José Saramago",
      country: "Portugal",
      imageLink: "https://i.ibb.co/jG2FRmC/blindness.jpg",
      is_liked: true,
      language: "Portuguese",
      link: "https://en.wikipedia.org/wiki/Blindness_(novel) ",
      pages: 352,
      price: 59,
      rating: 5,
      reviews: 82,
      title: "Blindness",
      year: 1995
    },
    {
      author: "William Shakespeare",
      country: "England",
      imageLink: "https://i.ibb.co/J3LfyC9/hamlet.jpg",
      is_liked: false,
      language: "English",
      link: "https://en.wikipedia.org/wiki/Hamlet ",
      pages: 432,
      price: 8,
      rating: 5,
      reviews: 430,
      title: "Hamlet",
      year: 1603
    },
    {
      author: "William Shakespeare",
      country: "England",
      imageLink: "https://i.ibb.co/LRnTmLk/king-lear.jpg",
      is_liked: true,
      language: "English",
      link: "https://en.wikipedia.org/wiki/King_Lear ",
      pages: 384,
      price: 75,
      rating: 1,
      reviews: 54,
      title: "King Lear",
      year: 1608
    },
    {
      author: "William Shakespeare",
      country: "England",
      imageLink: "https://i.ibb.co/b6D2V6k/othello.jpg",
      is_liked: false,
      language: "English",
      link: "https://en.wikipedia.org/wiki/Othello ",
      pages: 314,
      price: 17,
      rating: 4,
      reviews: 237,
      title: "Othello",
      year: 1609
    },
    {
      author: "Sophocles",
      country: "Greece",
      imageLink: "https://i.ibb.co/SQKvPq2/oedipus-the-king.jpg",
      is_liked: true,
      language: "Greek",
      link: "https://en.wikipedia.org/wiki/Oedipus_the_King ",
      pages: 88,
      price: 23,
      rating: 2,
      reviews: 392,
      title: "Oedipus the King",
      year: 430
    },
    {
      author: "Stendhal",
      country: "France",
      imageLink: "https://i.ibb.co/RjqHvKM/le-rouge-et-le-noir.jpg",
      is_liked: false,
      language: "French",
      link: "https://en.wikipedia.org/wiki/The_Red_and_the_Black ",
      pages: 576,
      price: 12,
      rating: 4,
      reviews: 345,
      title: "The Red and the Black",
      year: 1830
    },
    {
      author: "Laurence Sterne",
      country: "England",
      imageLink: "https://i.ibb.co/m0n3fph/the-life-and-opinions-of-tristram-shandy.jpg",
      is_liked: true,
      language: "English",
      link: "https://en.wikipedia.org/wiki/The_Life_and_Opinions_of_Tristram_Shandy,_Gentleman ",
      pages: 640,
      price: 81,
      rating: 3,
      reviews: 256,
      title: "The Life And Opinions of Tristram Shandy",
      year: 1760
    },
    {
      author: "Italo Svevo",
      country: "Italy",
      imageLink: "https://i.ibb.co/RHCDHJ5/confessions-of-zeno.jpg",
      is_liked: false,
      language: "Italian",
      link: "https://en.wikipedia.org/wiki/Zeno%27s_Conscience ",
      pages: 412,
      price: 80,
      rating: 2,
      reviews: 181,
      title: "Confessions of Zeno",
      year: 1923
    },
    {
      author: "Jonathan Swift",
      country: "Ireland",
      imageLink: "https://i.ibb.co/ynJh2Rz/gullivers-travels.jpg",
      is_liked: true,
      language: "English",
      link: "https://en.wikipedia.org/wiki/Gulliver%27s_Travels ",
      pages: 178,
      price: 30,
      rating: 2,
      reviews: 103,
      title: "Gulliver's Travels",
      year: 1726
    },
    {
      author: "Leo Tolstoy",
      country: "Russia",
      imageLink: "https://i.ibb.co/Mk2j3md/war-and-peace.jpg",
      is_liked: false,
      language: "Russian",
      link: "https://en.wikipedia.org/wiki/War_and_Peace ",
      pages: 1296,
      price: 11,
      rating: 3,
      reviews: 111,
      title: "War and Peace",
      year: 1867
    },
    {
      author: "Leo Tolstoy",
      country: "Russia",
      imageLink: "https://i.ibb.co/LQvqhsq/anna-karenina.jpg",
      is_liked: true,
      language: "Russian",
      link: "https://en.wikipedia.org/wiki/Anna_Karenina ",
      pages: 864,
      price: 90,
      rating: 4,
      reviews: 447,
      title: "Anna Karenina",
      year: 1877
    },
    {
      author: "Leo Tolstoy",
      country: "Russia",
      imageLink: "https://i.ibb.co/BGYsSsX/the-death-of-ivan-ilyich.jpg",
      is_liked: false,
      language: "Russian",
      link: "https://en.wikipedia.org/wiki/The_Death_of_Ivan_Ilyich ",
      pages: 92,
      price: 23,
      rating: 0,
      reviews: 170,
      title: "The Death of Ivan Ilyich",
      year: 1886
    },
    {
      author: "Mark Twain",
      country: "United States",
      imageLink: "https://i.ibb.co/yRBJ2KY/the-adventures-of-huckleberry-finn.jpg",
      is_liked: true,
      language: "English",
      link: "https://en.wikipedia.org/wiki/Adventures_of_Huckleberry_Finn ",
      pages: 224,
      price: 10,
      rating: 5,
      reviews: 308,
      title: "The Adventures of Huckleberry Finn",
      year: 1884
    },
    {
      author: "Valmiki",
      country: "India",
      imageLink: "https://i.ibb.co/kHKBnZh/ramayana.jpg",
      is_liked: false,
      language: "Sanskrit",
      link: "https://en.wikipedia.org/wiki/Ramayana ",
      pages: 152,
      price: 62,
      rating: 3,
      reviews: 169,
      title: "Ramayana",
      year: 450
    },
    {
      author: "Virgil",
      country: "Roman Empire",
      imageLink: "https://i.ibb.co/wsdQWkX/the-aeneid.jpg",
      is_liked: true,
      language: "Classical Latin",
      link: "https://en.wikipedia.org/wiki/Aeneid ",
      pages: 442,
      price: 59,
      rating: 1,
      reviews: 42,
      title: "The Aeneid",
      year: 23
    },
    {
      author: "Vyasa",
      country: "India",
      imageLink: "https://i.ibb.co/7YY6t2d/the-mahab-harata.jpg",
      is_liked: false,
      language: "Sanskrit",
      link: "https://en.wikipedia.org/wiki/Mahabharata ",
      pages: 276,
      price: 53,
      rating: 2,
      reviews: 412,
      title: "Mahabharata",
      year: 700
    },
    {
      author: "Walt Whitman",
      country: "United States",
      imageLink: "https://i.ibb.co/jMNXbJ1/leaves-of-grass.jpg",
      is_liked: true,
      language: "English",
      link: "https://en.wikipedia.org/wiki/Leaves_of_Grass ",
      pages: 152,
      price: 13,
      rating: 5,
      reviews: 269,
      title: "Leaves of Grass",
      year: 1855
    },
    {
      author: "Virginia Woolf",
      country: "United Kingdom",
      imageLink: "https://i.ibb.co/rGXc9vG/mrs-dalloway.jpg",
      is_liked: false,
      language: "English",
      link: "https://en.wikipedia.org/wiki/Mrs_Dalloway ",
      pages: 216,
      price: 66,
      rating: 5,
      reviews: 298,
      title: "Mrs Dalloway",
      year: 1925
    },
    {
      author: "Virginia Woolf",
      country: "United Kingdom",
      imageLink: "https://i.ibb.co/hyMX30f/to-the-lighthouse.jpg",
      is_liked: true,
      language: "English",
      link: "https://en.wikipedia.org/wiki/To_the_Lighthouse ",
      pages: 209,
      price: 56,
      rating: 1,
      reviews: 216,
      title: "To the Lighthouse",
      year: 1927
    },
    {
      author: "Marguerite Yourcenar",
      country: "France/Belgium",
      imageLink: "https://i.ibb.co/TKXmH7h/memoirs-of-hadrian.jpg",
      is_liked: false,
      language: "French",
      link: "https://en.wikipedia.org/wiki/Memoirs_of_Hadrian ",
      pages: 408,
      price: 81,
      rating: 2,
      reviews: 258,
      title: "Memoirs of Hadrian",
      year: 1951
    }
  ]